### ISSUE TITLE
Playbook detecting changes

### ISSUE THREAD

**Issue by haodeon** [fortinet-solutions-cse/ansible_fgt_modules#11]
Hi,

I've been slowly developing my playbook for configuring a NVA pair of Fortigates in Azure. These modules have been super helpful in achieving that goal.

One thing which I find a bit odd with these modules is every time I run the playbook the output tells me the task has changed something when it is not true.

Is this expected behaviour?

**Comment by mamunozgonzalez** [comment]
Hi @haodeon,
 thanks for your feedback. We are glad to be of help for your project.

And yes, the behaviour you see is the expected one. In the current status of development the modules sent one single request (PUT/POST) directly to Fortigate, so there is no comparison between the previous and current state of config. The goal was to minimize the requests and maximize the performance.

This is something we plan to fix in the future but since it is a non critical feature and it imposes a bit of more load in the execution we wanted to pospone it for later and only do it if customers are really interested about it: The fix will be to add at least one GET (or maybe two) to check if the configuration was actually changed, hence execution will be slighly slower (though only noticeable when running a really large amount of tasks on FGT).

**Comment by haodeon** [comment]
When I started I put everything into one play. This was enough as the configuration was small.

Now that my configuration is getting larger I've divided the tasks into roles and then tagged the roles. I am handling minimising the number of requests being sent by only running certain tagged roles.

It would be good however to have Ansible detect if a configuration was really changed. This way we have a way to know if configuration has drifted.

**Comment by mamunozgonzalez** [comment]
Yes, we have it in the backlog and will give it more prio now.

**Comment by mamunozgonzalez** [comment]
Hi @haodeon ,
We discussed internally about this topic and it'll be addressed in optimal way in future versions of FGT (requiring a modification in both Ansible and FGT). The modification will minimize the requests issued to FortiGate, thus giving a much better user experience.

**Comment by haodeon** [comment]
Hi @mamunozgonzalez 
Thanks for the update. I wasn't expecting an update so soon but this is awesome.

**Comment by sbraz** [comment]
Hi @mamunozgonzalez, have there been any changes in the API regarding this issue?

**Comment by chillancezen** [comment]
@sbraz hi Louis,
this revision-change feature has been checked in generator: https://github.com/fortinet-solutions-cse/ansible_generator/pull/17

**Comment by sbraz** [comment]
Thanks, very nice, I guess this issue can almost be closed then? How often do you regenerate the modules from the templates?

**Comment by chillancezen** [comment]
> Thanks, very nice, I guess this issue can almost be closed then? How often do you regenerate the modules from the templates?

hi Louis, 

after a discussion with my manager. we decide not to do generation right now . 
every minor change results in changes in every module(we have over 400 modules). we accumulate the patches for generator for a period and synchronize with upstream. 

however, the upstream is being migrated to Ansible Galaxy collection. anyway, I will let you know once we have to generate it. 

thanks, 
Link

**Comment by mamunozgonzalez** [comment]
This repository will be set to archived soon. Please report any new issue to: https://github.com/fortinet-ansible-dev/ansible-galaxy-fortios-collection/issues
