### ISSUE TITLE
Modules fail if the "state" parameter is not provided

### ISSUE THREAD

**Issue by sbraz** [fortinet-solutions-cse/ansible_fgt_modules#26]
When the `state` attribute isn't provided, the `state` variable is set to `None` because the second clause of the `if` matches. The third clause never matches and even if it did, I don't see why you would want to set `state` to `True`.

https://github.com/fortinet-solutions-cse/ansible_fgt_modules/blob/dfed70ded3e3ec5dc103831cb8130b926a2885d0/v6.0.6/system/fortios_system_interface.py#L2058-L2078

**Comment by chillancezen** [comment]
hi Louis,

Thanks for the issue. 

we have the policy for modules added in later than 2.8: the `state` migrated to the outer as top-level parameter. 

that's to say: 

- for modules added in 2.8, `state` co-exists as outer and inner parameters and both of them are marked as `required = false`
- for modules added later in 2.9 and since,  `state` is only top-level parameter and marked as `required = true`



that's why we have the code to select the actual `state`:

- for modules added in 2.8, outer `state` parameter is always preferred.  if outer `state` is not present, then inner `state` is queried. if inner one is not given either, a value must be assigned to variable __`state`__  and module fails gracefully.  if we don't specify `state = True`, there will be a runtime syntax error here.  As a matter of fact, the value of `state` can be anything other than `present` or `absent`. 

- for modules added later than 2.8.  you always have a `state` because it's mandatorily inputed.  things are getting much simpler as you can see: https://github.com/ansible/ansible/blob/devel/lib/ansible/modules/network/fortios/fortios_vpn_ssl_web_realm.py#L238

this is a legacy issue we encountered during migrating fields. 

Louis, could you please consider closing it. ?

again thanks for filing this issue. 

also cc @frankshen01 @mamunozgonzalez

**Comment by chillancezen** [comment]
as for the fix, I will make a patch in generator first to make it clear the second clause is querying the inner parameter `state`:

```
if 'state' in data and data['state']: 
     state = data['state'] 
 elif 'state' in data['system_interface'] and data['system_interface']['state']: 
     state = data['system_interface']['state'] 
 else: 
     state = True 
```

**Comment by sbraz** [comment]
> for modules added in 2.8, state co-exists as outer and inner parameters and both of them are marked as required = false

Then why does it fail when it is not specified anywhere? If it's not required, it shouldn't fail when it isn't provided.

**Comment by mamunozgonzalez** [comment]
Hi,
 I answered in the PR (please check https://github.com/fortinet-solutions-cse/ansible_generator/pull/18#issuecomment-572998971)

If there are other different failures after the fix (due to "else: state = True") please feel free to open another issue/PR
